### ISSUE TITLE
Clipping Issue for Spider webs (Mage Arena entrance and Tree near lever)

### ISSUE THREAD

**Issue by syuil** [RSPSApp/elvarg-rsps#171]
https://streamable.com/553avh

This only happens with the 3 spider webs from the title, it looks like the tile in front of them are clipped so you cant stand on that tile in front until you slash the web, if web appears while you're on that title you can noclip through the web.

**Comment by tobywisener** [comment]
I think the fix for this is to change these objects to type 0 in the map data. These are type 10 whereas the other webs inside the mb out building are type 0 and you can't replicate this. The reason you can walk through them when you're already on the tile is that rs pathing allows you to walk off an object if you're standing directly on it. So I'm tagging this with cache as the fix is to edit the region on our copy of RSPSi and replace those webs with type 0 (same object I'd 733 iirc)
